# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# environment variables set for all builds
env:
  global:
    - BIOC_USE_DEVEL="FALSE"  ## Use the current release version

r:
  - release

# we need to install BiocInstaller for testing Bioconductor packages
bioc_required: true

# SynSigGen and PCAWG7 should be from GitHub, rather than CRAN.
# (GitHub contains develop functionalities)
r_github_packages:
  - steverozen/SynSigGen
  - steverozen/PCAWG7
  - steverozen/ICAMSxtra

addons:
  apt:
    packages:
      - libgit2-dev
