# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - oldrel
  - release
  - devel

bioc_packages: BiocManager, DelayedArray, BSGenome,
GenomeInfoDb, GenomicRanges, IRanges, Biostrings




